DigitalMusicAnalysis::MainWindow
pitchConv
WaveFileReader DigitalMusicAnalysis.MainWindow.waveReader
Referenced by DigitalMusicAnalysis.MainWindow.loadWave, DigitalMusicAnalysis.MainWindow.playBack.
wavefile DigitalMusicAnalysis.MainWindow.waveIn
Referenced by DigitalMusicAnalysis.MainWindow.freqDomain, DigitalMusicAnalysis.MainWindow.loadWave, DigitalMusicAnalysis.MainWindow.onsetDetection, DigitalMusicAnalysis.MainWindow.readXML.
timefreq DigitalMusicAnalysis.MainWindow.stftRep
Referenced by DigitalMusicAnalysis.MainWindow.freqDomain, DigitalMusicAnalysis.MainWindow.onsetDetection.
float [] DigitalMusicAnalysis.MainWindow.pixelArray
Referenced by DigitalMusicAnalysis.MainWindow.freqDomain, DigitalMusicAnalysis.MainWindow.loadImage.
musicNote [] DigitalMusicAnalysis.MainWindow.sheetmusic
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow, DigitalMusicAnalysis.MainWindow.onsetDetection.
WaveOut DigitalMusicAnalysis.MainWindow.playback
Referenced by DigitalMusicAnalysis.MainWindow.playBack, DigitalMusicAnalysis.MainWindow.updateSlider.
Complex [] DigitalMusicAnalysis.MainWindow.twiddles
Referenced by DigitalMusicAnalysis.MainWindow.fft, DigitalMusicAnalysis.MainWindow.onsetDetection.
Complex [] DigitalMusicAnalysis.MainWindow.compX
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection.
string DigitalMusicAnalysis.MainWindow.filename
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow, DigitalMusicAnalysis.MainWindow.replay.
double DigitalMusicAnalysis.MainWindow.bpm
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection, DigitalMusicAnalysis.MainWindow.readXML.
DigitalMusicAnalysis.MainWindow.MainWindow()
References DigitalMusicAnalysis.MainWindow.closeMusic, DigitalMusicAnalysis.MainWindow.filename, DigitalMusicAnalysis.MainWindow.freqDomain, DigitalMusicAnalysis.MainWindow.loadHistogram, DigitalMusicAnalysis.MainWindow.loadImage, DigitalMusicAnalysis.MainWindow.loadWave, DigitalMusicAnalysis.MainWindow.onsetDetection, DigitalMusicAnalysis.MainWindow.playBack, DigitalMusicAnalysis.MainWindow.readXML, DigitalMusicAnalysis.MainWindow.sheetmusic, DigitalMusicAnalysis.MainWindow.updateHistogram, DigitalMusicAnalysis.MainWindow.updateSlider, DigitalMusicAnalysis.MainWindow.zoomIN, DigitalMusicAnalysis.MainWindow.zoomOUT.
void DigitalMusicAnalysis.MainWindow.loadImage()
References DigitalMusicAnalysis.MainWindow.pixelArray.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.loadHistogram()
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow, DigitalMusicAnalysis.MainWindow.updateHistogram.
void DigitalMusicAnalysis.MainWindow.zoomIN(object sender, RoutedEventArgs e)
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.zoomOUT(object sender, RoutedEventArgs e)
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
string DigitalMusicAnalysis.MainWindow.openFile(string title)
void DigitalMusicAnalysis.MainWindow.loadWave(string filename)
References DigitalMusicAnalysis.MainWindow.waveIn, DigitalMusicAnalysis.MainWindow.waveReader.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow, DigitalMusicAnalysis.MainWindow.replay.
void DigitalMusicAnalysis.MainWindow.freqDomain()
References DigitalMusicAnalysis.MainWindow.pixelArray, DigitalMusicAnalysis.MainWindow.stftRep, DigitalMusicAnalysis.wavefile.wave, DigitalMusicAnalysis.MainWindow.waveIn.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.onsetDetection()
References DigitalMusicAnalysis.MainWindow.bpm, DigitalMusicAnalysis.MainWindow.ClearStats, DigitalMusicAnalysis.MainWindow.compX, DigitalMusicAnalysis.MainWindow.DisplayStats, DigitalMusicAnalysis.MainWindow.fft, DigitalMusicAnalysis.wavefile.SampleRate, DigitalMusicAnalysis.MainWindow.sheetmusic, DigitalMusicAnalysis.MainWindow.stftRep, DigitalMusicAnalysis.MainWindow.stringMatch, DigitalMusicAnalysis.timefreq.timeFreqData, DigitalMusicAnalysis.MainWindow.twiddles, DigitalMusicAnalysis.MainWindow.waveIn.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.DisplayStats(object sender, System.Windows.Input.MouseEventArgs e)
References DigitalMusicAnalysis.musicNote.error, DigitalMusicAnalysis.musicNote.pitch.
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection.
void DigitalMusicAnalysis.MainWindow.ClearStats(object sender, System.Windows.Input.MouseEventArgs e)
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection.
void DigitalMusicAnalysis.MainWindow.updateHistogram(object sender, RoutedEventArgs e)
References DigitalMusicAnalysis.MainWindow.loadHistogram.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.playBack()
References DigitalMusicAnalysis.MainWindow.playback, DigitalMusicAnalysis.MainWindow.waveReader.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow, DigitalMusicAnalysis.MainWindow.replay.
void DigitalMusicAnalysis.MainWindow.updateSlider()
References DigitalMusicAnalysis.MainWindow.playback.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
void DigitalMusicAnalysis.MainWindow.Window_Loaded(object sender, RoutedEventArgs e)
void DigitalMusicAnalysis.MainWindow.button3_Click(object sender, RoutedEventArgs e)
void DigitalMusicAnalysis.MainWindow.button4_Click(object sender, RoutedEventArgs e)
void DigitalMusicAnalysis.MainWindow.replay(object sender, RoutedEventArgs e)
References DigitalMusicAnalysis.MainWindow.filename, DigitalMusicAnalysis.MainWindow.loadWave, DigitalMusicAnalysis.MainWindow.playBack.
void DigitalMusicAnalysis.MainWindow.closeMusic(object sender, EventArgs e)
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
Complex [] DigitalMusicAnalysis.MainWindow.fft(Complex[] x, int L)
References DigitalMusicAnalysis.MainWindow.E, DigitalMusicAnalysis.MainWindow.twiddles.
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection.
musicNote [] DigitalMusicAnalysis.MainWindow.readXML(string filename)
References DigitalMusicAnalysis.MainWindow.bpm, DigitalMusicAnalysis.wavefile.SampleRate, DigitalMusicAnalysis.MainWindow.waveIn.
Referenced by DigitalMusicAnalysis.MainWindow.MainWindow.
string [] DigitalMusicAnalysis.MainWindow.stringMatch(string A, string B)
References DigitalMusicAnalysis.MainWindow.F.
Referenced by DigitalMusicAnalysis.MainWindow.onsetDetection.
string [] DigitalMusicAnalysis.MainWindow.stringMatch(int[] A, int[] B)
References DigitalMusicAnalysis.MainWindow.F.